[feishu]
# 飞书应用凭据（必填）
# https://open.feishu.cn/app/  选择你的应用, 查看app_id 和 app_secret 并进入 '安全设置' 页面, 在 '重定向URL'  中填写本机ip和本机端口, 端口号可自定义, 比如: http://localhost:9721/callback
app_id =
app_secret =

# '重定向URL' 中定义的本机回调端口号
redirect_port = 9721

# 要监听的飞书群组名称,可多个, 逗号分隔
chat_names =

[imguploader]
# 本地图片上传到imgbb图床所使用的key
imgbb_key =


[robot]
# 流程结束后用于发送给钉钉机器人的通知
# 钉钉机器人的access_token值,空表表示不通知
accessToken =
# 飞书自定义机器人token
# 会拼接成: https://open.feishu.cn/open-apis/bot/v2/hook/{feishuToken}
feishuToken =

# 钉钉群聊机器人开启加签模式后, 需要传入secret参数
secret =

# 群聊机器人安全设置添加的关键词信息,会拼接在消息开头, 钉钉/飞书均支持该属性
keyWord = 测试

# 需要@的人员手机号，可多个，逗号分隔, 当前只支持钉钉机器人,飞书不支持
atPhone =

# 是否at所有人, 钉钉/飞书均支持
atAll = False

# 额外的信息,会拼接到keyword下方,钉钉/飞书均支持
extraInfo =


